global using System.Collections.Generic;
global using System;
global using System.Linq;
global using System.Text;
global using System.Collections;
global using System.Diagnostics;
global using System.IO;
global using SunamoLogging.Base;
global using SunamoLogging._sunamo.SunamoCollectionsIndexesWithNull;
global using SunamoLogging._sunamo.SunamoThisApp;
global using SunamoLogging._public.SunamoEnums.Enums;
global using SunamoLogging._public.SunamoInterfaces.Interfaces;
global using SunamoLogging._sunamo.SunamoExceptions;
global using SunamoLogging._sunamo.SunamoLang.SunamoI18N;
global using SunamoLogging._sunamo.SunamoValues.Constants;
global using SunamoLogging._sunamo.SunamoShared.Helpers.Runtime;
global using SunamoLogging._sunamo;
global using Microsoft.Extensions.Logging;
global using System.Reflection;
global using System.Net;
global using SunamoLogging.Logger.LoggerBaseNS;
global using SunamoLogging._sunamo.SunamoValues;
global using System.Diagnostics.CodeAnalysis;
global using SunamoLogging;
global using SunamoLogging.FileLogger;
global using SunamoLogging.Services;
global using SunamoLogging.Logger.TemplateLoggerBaseNS;
global using SunamoLogging.Logger.TypedLoggerBaseNS;
global using SunamoLogging._sunamo.SunamoStringJoinPairs;

global using System.Dynamic;
global using System.Text.Json;
global using System.Threading.Tasks;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
