name: Build SunamoLogging

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoLogging
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoLogging/SunamoLogging.csproj

    - name: Build
      run: dotnet build SunamoLogging/SunamoLogging.csproj --configuration Release --no-restore

  test:
    name: Test SunamoLogging.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoLogging.Tests/SunamoLogging.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoLogging.Tests/SunamoLogging.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoLogging.Tests/SunamoLogging.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
